language: c
compiler:
  - gcc
  - clang
env:
  - LIBUSB=libusb EXTRA=libusb-dev
  - LIBUSB=libusb-1.0 EXTRA=libusb-1.0-0-dev
script:
  - ./build-and-test.sh
before_install:
  - sudo apt-get update; sudo apt-get install -qq libyubikey-dev $EXTRA
matrix:
  include:
    - compiler: gcc
      env: LIBUSB=windows EXTRA=wine
